- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MappingGeneratorImpl.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/NullTest.java
* Fixes NullPointerException on attempting to access getClass of null object.
* Fixes silently ignoring nulls within a list/array when they are contained by a higher object.
> JOHNZON-151: Fix serialization of nulls inside a collection inside a parent object

- johnzon-core/src/main/java/org/apache/johnzon/core/JsonObjectImpl.java
- johnzon-core/src/main/java/org/apache/johnzon/core/Strings.java
- johnzon-core/src/test/java/org/apache/johnzon/core/JsonObjectImplTest.java
This PR will fix JOHNZON-209 with additional test cases.
> JOHNZON-209 Fix JsonObject#toString() to escape key names.

- pom.xml
- src/site/markdown/index.md
Proposed fix for the JohnzonAny annotation documentation. For my local builds, I have Maven 3.6 and I had to bump findbugs in pom.xml to 3.0.4 otherwise I ran into a compatibility issue. Feel free to ignore that commit, it was only needed to build the documentation fix.
> Fix documentation for @JohnzonAny

- johnzon-json-extras/src/main/java/org/apache/johnzon/jsonb/extras/polymorphism/Polymorphic.java
`No @Id` -> `No @JsonId`
`No @Classes` ->`No @JsonChildren`
> Fixed typo in error message re: missing annotations

- src/site/markdown/index.md
Explicitly warning that binding of Polymorphic.(De)Serializer MUST NOT be done by with(De)Serializer, as @rmannibucau said this is by design *only* working with annotation-binding.
(Continuation from https://github.com/eclipse-ee4j/jsonb-api/issues/147#issuecomment-523833911)
> Explicit note that Polymorphic does not support withSerializers / withDeserializers

- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/serializer/JohnzonDeserializationContext.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/serializer/DeserializationContextTest.java
@rmannibucau Before filing another bug report I think it is better to show you this draft. It seems this time I really detected a bug. So we can discuss BEFORE posting this code to JIRA. :-)
> [JOHNZON-277] Fails to deserialize inner empty JSON block {} at OBJECT_START

- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/serializer/DeserializationContextTest.java
Tried to reproduce the bug multiple times on Windows and Linux, but it did not happen anymore. The reason why this test was disabled seems to be gone. Hence it seems it was a local instability on my side, and it should be safe to enable this test now. Sorry for the confusion! :-)
> Enabled test as it seems to run well.

- johnzon-core/src/main/java/org/apache/johnzon/core/JsonArrayBuilderImpl.java
- johnzon-core/src/main/java/org/apache/johnzon/core/JsonObjectBuilderImpl.java
- pom.xml
Even in these days of modern Java, reducing memory consumption, GC stress and memory fragmentation, are beneficial side aspects.
If makes no sense to create new **empty** instances of JsonArray and JsonObject again and again. For this case, JSON-P provides special **constants**.
It makes sense to return these constants always.
> [JOHNZON-278] Return constant instead of new instance of empty block / empty array

- johnzon-maven-plugin/src/test/java/org/apache/johnzon/maven/plugin/ExampleToModelMojoTest.java
```bash
$ git clone https://github.com/apache/johnzon.git
$ cd johnzon
$ mvn clean install
...
[INFO] Running org.apache.johnzon.maven.plugin.ExampleToModelMojoTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.172 s <<< FAILURE! - in org.apache.johnzon.maven.plugin.ExampleToModelMojoTest
[ERROR] generate(org.apache.johnzon.maven.plugin.ExampleToModelMojoTest) Time elapsed: 0.125 s <<< FAILURE!
org.junit.ComparisonFailure:
expected:</*[
{{ * Licensed to the Apache Software Foundation (ASF) under one}}
...
> JOHNZON-272 Fails to build Johnzon :: Maven Plugin

- johnzon-maven-plugin/.gitattributes
- johnzon-maven-plugin/src/test/java/org/apache/johnzon/maven/plugin/ExampleToModelMojoTest.java
Using `.gitattributes` to guarantee LF line endings instead of explicitly replacing wrong line endings in Java code.
See https://github.com/apache/johnzon/pull/50#issuecomment-534668791.
I confirm it actually solves JOHNZON-272 on both, Linux (tried with Gitpod) and Windows (tried with Windows 8.1).
> JOHNZON-272 Fails to build Maven Plugin - Alternative Solution

- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/DefaultPropertyVisibilityStrategy.java
According to apparent concensus among the Johnzon contributors, the class `DefaultPropertyVisibilityStrategy` should not be `public` anymore.
This in turn reduces the need to fix [JOHNZON-276](https://issues.apache.org/jira/browse/JOHNZON-276) by #44.
Closes [JOHNZON-286](https://issues.apache.org/jira/browse/JOHNZON-286).
> JOHNZON-286 Making DefaultPropertyVisibilityStrategy non-public

- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/Mapper.java
This fixes an issue with JAX-RS in TomEE 7.0.x when serializing objects with non-ASCII characters on machines where the default charset is not an UTF-8.
> Use the configured charset instead of always relying on the default one (backport from 'master')

- johnzon-core/src/main/java/org/apache/johnzon/core/JsonPointerImpl.java
- johnzon-core/src/test/java/org/apache/johnzon/core/JsonPointerTest.java
Currently it is not allowed to remove an entry by using a `-` as array index.
Since it is allowed for the add operation, it should also be allowed for all the other operations.
Further this is necessary if johnzon is used together with the JSON Patch library.
I've added a check for the `-` index in the `getArrayIndex` method to return the index of the last entry.
Additionally I've made the check in the `validateArrayIndex` more explicit.
One test that perform a remove with a `-` as array index.
> Added possibility to use minus as array index for the remove operation.

- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/JohnzonJsonb.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JohnzonJsonbTest.java
This PR ensures that toArray() is called in JohnzonJsonB so primitive arrays are handled correctly. Tests have been added for arrays of each primitive type.
> JOHNZON-326 Fix for handling primitive arrays in JsonB

- johnzon-jsonschema/src/main/java/org/apache/johnzon/jsonschema/JsonSchemaValidatorFactory.java
- johnzon-jsonschema/src/main/java/org/apache/johnzon/jsonschema/spi/builtin/IntegerValidation.java
- johnzon-jsonschema/src/main/java/org/apache/johnzon/jsonschema/spi/builtin/MultipleOfValidation.java
- johnzon-jsonschema/src/main/java/org/apache/johnzon/jsonschema/spi/builtin/TypeValidation.java
- johnzon-jsonschema/src/test/java/org/apache/johnzon/jsonschema/JsonSchemaValidatorTest.java
Hi!
As per the official json-schema specification, integer type validation is missing from the current implementation.
http://json-schema.org/understanding-json-schema/reference/numeric.html
This PR tries to tackle that in the least intrusive way possible.
Thanks in advance!
> [JOHNZON-327] Json Schema Validation: added integer type validation.

- johnzon-core/src/main/java/org/apache/johnzon/core/JohnzonJsonParserImpl.java
- johnzon-core/src/test/java/org/apache/johnzon/core/JsonParserStreamingTest.java
As the comments say, `getArrayStream()` and `getObjectStream()` were very simplistic and didn't conform to the spirit of the specification, which requires lazy loading from the underlying stream.
Now these methods should behave lazily, only keeping the minimal amount of data in memory that's necessary for the stream.
> True object and array streaming

- johnzon-core/src/main/java/org/apache/johnzon/core/Buffered.java
- johnzon-core/src/main/java/org/apache/johnzon/core/JsonGeneratorFactoryImpl.java
- johnzon-core/src/main/java/org/apache/johnzon/core/Snippet.java
- johnzon-core/src/test/java/org/apache/johnzon/core/SnippetTest.java
- johnzon-jaxrs/src/main/java/org/apache/johnzon/jaxrs/ConfigurableJohnzonProvider.java
- johnzon-jaxrs/src/main/java/org/apache/johnzon/jaxrs/WildcardConfigurableJohnzonProvider.java
- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/JohnzonBuilder.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/SnippetMaxLengthTest.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MapperBuilder.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MapperConfig.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MappingParserImpl.java
This appears in a stacktrace like the following
```
javax.json.bind.JsonbException: Can't map JSON Object to class java.lang.String: {"rendered":"Privacy Policy"}
at org.apache.johnzon.jsonb.JohnzonJsonb.fromJson(JohnzonJsonb.java:89)
```
> Show a chunk of json when mapping the object fails

- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/DeserializationExceptionMessagesTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/ExceptionAsserts.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbAdapterExceptionsTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbBeanConstructorExceptionsTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbBeanGetterUserExceptionsTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbBeanSetterUserExceptionsTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbCreatorExceptionsTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbSerializerExceptionsTest.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/SnippetMaxLengthTest.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/ExceptionMessages.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/FactoryCreateException.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MappingParserImpl.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MissingFactoryException.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/SetterMappingException.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/DeserializationExceptionMessagesTest.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/ExceptionAsserts.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/MapperAdapterExceptionsTest.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/MapperBeanConstructorExceptionsTest.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/MapperBeanGetterUserExceptionsTest.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/MapperBeanSetterUserExceptionsTest.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/MapperConverterExceptionsTest.java
- johnzon-mapper/src/test/java/org/apache/johnzon/mapper/TypeSimpleNameTest.java
Addresses:
- [JOHNZON-370](https://issues.apache.org/jira/browse/JOHNZON-370) Include class, property, type and json value in mapping exceptions
- [JOHNZON-371](https://issues.apache.org/jira/browse/JOHNZON-371) NullPointerException thrown when null value present in primitive arrays
- [JOHNZON-372](https://issues.apache.org/jira/browse/JOHNZON-372) Entire json value serialized in exception
See PR #90 for a view of what the exceptions look like as they are currently in 1.2.18
> Exception message improvements

- .github/workflows/maven.yml
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/JsonbRecordTest.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/Adapter.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/JohnzonRecord.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/internal/JsonPointerTracker.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/util/BeanUtil.java
- johnzon-maven-plugin/pom.xml
- johnzon-osgi/pom.xml
- johnzon-websocket/pom.xml
- pom.xml
building on the work done by @hboutemy in PR #93, and the javadoc fixes in PR #95, these changes fix some outstanding errors with Javadoc and aim to improve the build by making sure that maven plugins are defined in the root johnzon pom within the _pluginManagement_ section. 
In the case of the cobertura plugin, I've removed it entirely as it's been defunct for some time and Jacoco should be used instead. I've swapped the now dead findbugs plugin for spotbugs (more changes need to use v4 though). The checkstyle plugin needs further changes which can be in a future PR. I've also enabled javadoc linting as it no longer fails.
> update maven plugins

- tck/jsonb/pom.xml
Going for some low hanging fruit here, simple configuration change that "fixes" two NumberFormatCustomizationTest tests when running on JDK 13+ (see https://github.com/jakartaee/jsonb-api/issues/272)
Also quickly documented on the system properties introduced in https://github.com/apache/johnzon/pull/103
This brings failing jsonb TCK tests down from:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SerializersCustomizationCDITest.testCDISupport:110 Failed to correctly unmarshall complex type hierarchy using a serializer configured using JsonbTypeSerializer annotation and a deserializer with a CDI managed field configured using JsonbTypeDeserializer annotation.
Expected: is <ee.jakarta.tck.json.bind.cdi.customizedmapping.serializers.model.AnimalShelterWithInjectedSerializer@672037ff …
```
> Fix NumberFormatCustomizationTest when running on JDK 13+

- tck/jsonb/pom.xml
- tck/jsonp/pom.xml
- tck/pom.xml
This is the counterpart to #110 and fixes all remaining TCK tests for JSON-P (pluggability and JSONPSigTest) and also fixes JSONBSigTest for JSON-B
Took orientation from how [JSON-P](https://github.com/jakartaee/jsonp-api/tree/2.1.1-tck/tck/tck-dist-eftl/src/main/bin) and [JSON-B](https://github.com/jakartaee/jsonb-api/tree/3.0.0-tck/tck-dist/src/main/bin) TCKs are apparently supposed to be run. Feel free to suggest changes as I've never dealt with something like this before
> Fix pluggability and SigTests TCKs

- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/polymorphism/JsonbPolymorphismTest.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MappingGeneratorImpl.java
> [JOHNZON-401] fix serialization of nested polymorphic objects

- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/JsonbMappings.java
- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/polymorphism/JsonbPolymorphismHandler.java
- johnzon-jsonb/src/main/java/org/apache/johnzon/jsonb/polymorphism/JsonbPolymorphismTypeInfo.java
- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/polymorphism/JsonbPolymorphismTest.java
This resolves [JOHNZON-402](https://issues.apache.org/jira/projects/JOHNZON/issues/JOHNZON-402)
TCKs still pass after this change, but the modules need their version to be changed from `2.0.0-SNAPSHOT` to `2.0.1-SNAPSHOT` (see #119)
> [JOHNZON-402] Reworked scanning for @JsonbTypeInfo annotations

- pom.xml
- src/site/markdown/download.md
- src/site/markdown/index.md
- src/site/site.xml
Fixes a few things I noticed while looking at the current site like broken links, javadoc not generating anymore, outdated download links, etc
Also Updates the site for JSON-P 2.1/JSON-B 3.0, documents properties I added in #103 and the removal of johnzon-jsonp-strict
> Site updates

- .github/workflows/maven.yml
Java 19 has been EOL for quite some time now + 21 is an LTS release
> Build on JDK 21

- johnzon-core/src/main/java/org/apache/johnzon/core/JsonStreamParserImpl.java
- johnzon-core/src/test/java/org/apache/johnzon/core/HugeStringTest.java
Resolves [JOHNZON-403](https://issues.apache.org/jira/browse/JOHNZON-403)
> [JOHNZON-403] improved long string perfomance

- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/internal/DelegatingInputStream.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/internal/DelegatingOutputStream.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/internal/DelegatingReader.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/internal/DelegatingWriter.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/internal/Streams.java
A `null` writer passed to the `Mapper.write` method, sensibly, throws an NPE upon flushing the buffer out. However, since the flushing occurs at a later time, debugging that this occurred is challenging. Thus, this commit implements a fail-fast `null` guard.
> Guard Mapper.write against null writer

- johnzon-core/src/main/java/org/apache/johnzon/core/JsonStreamParserImpl.java
reduce enum array allocation
use cached enum .values() 
https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/
> reduce enum array allocation

- johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/AdapterTest.java
- johnzon-mapper/src/main/java/org/apache/johnzon/mapper/MappingParserImpl.java
When using Field injection, null (missing) json values are naturally tolerated.
When using Constructor inject, null (missing) json values are explicitly tolerated in `MappingParserImpl.toObject`.  However, if an adapter was specified,  `MappingParserImpl.convertTo` would throw a null pointer as it did not have the same code to deal with null values.
> Tolerate null @JsonbCreator values when adapters are used
